# -*- coding: utf-8 -*-
"""LatestPINN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xY_Sc0QHhjodINE7bqBhQuc_M8oREn6s
"""

!pip install deepxde

import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import deepxde as dde
import seaborn as sns
import tensorflow as tf

A_0 = 0
R_0 = 1
I_0 = 0
S_0 = 0

y0 = [A_0, R_0, I_0, S_0]

beta = 0.001
q = 0.55
rho = 0.1
xi = 0.004
gamma = 0.008

parameters_real = {
    "beta": beta,
    "q": q,
    "rho": rho,
    "xi": xi,
    "gamma": gamma,
}

n_steps = 1500
noise_levels = [0.01, 0.05, 0.10, 0.20]
n_trials = 1

neurons = 64
layers = 3
activation = "swish"

#generate synthetic data

def generate_data(t_array, y0, beta, q, rho, xi, gamma):
  n_steps = len(t_array)
  states = np.zeros((n_steps, len(y0)))
  states[0] = y0

  for n in range(n_steps - 1):
    A, R, I, S = states[n]

    # Discrete update equations
    A_next = (
        A
        + 0.1 * (
            xi - gamma*A
        )
    )
    R_next = (
        R
        + 0.1 * (
            -q*A*R + beta*S
        )
    )
    I_next = (
        I
        + 0.1 * (
            q*A*R - rho*I
        )
    )
    S_next = (
        S
        + 0.1 * (
            rho*I - beta*S
        )
    )
    states[n+1] = [
        A_next,
        R_next,
        I_next,
        S_next,
    ]
  return states

# Generate the clean synthetic dataset ONCE
t_train = np.arange(0, n_steps + 1)[:, np.newaxis]

y_clean = generate_data(
    np.ravel(t_train),
    y0,
    beta,
    q,
    rho,
    xi,
    gamma
)

# Generate noisy versions only for plotting
for noise_val in noise_levels:
    print(f"Generating synthetic data with noise level: {noise_val*100:.0f}%")

    y_noisy = y_clean + (
        np.random.normal(
            loc=0,
            scale=y_clean.std(axis=0),
            size=y_clean.shape
        ) * noise_val
    )

    names = ["A", "R", "I", "S"]

    data_real = (
        pd.DataFrame(y_noisy, columns=names, index=t_train.ravel())
        .rename_axis("time")
        .reset_index()
        .melt(id_vars="time", var_name="status", value_name="skin")
    )

    fig, ax = plt.subplots(figsize=(7, 5))

    sns.lineplot(
        x="time",
        y="skin",
        hue="status",
        marker="o",
        linewidth=.5,
        markersize=3,
        markeredgecolor=None,
        data=data_real,
        ax=ax
    )

    ax.set(title=f"Synthetic Data with {noise_val*100:.0f}% Noise")
    fig.savefig("donkeysyntheticdata-noiseval" + str(noise_val) + ".png")
    fig.show()

def dinn(data_t, data_y, noise_level, variable_filename="variables.dat"):
    init_val = -2.197
    beta_raw = dde.Variable(init_val)
    q_raw = dde.Variable(init_val)
    rho_raw = dde.Variable(init_val)
    xi_raw = dde.Variable(init_val)
    gamma_raw = dde.Variable(init_val)

    variable_list = [
        beta_raw,
        q_raw,
        rho_raw,
        xi_raw,
        gamma_raw,
    ]


    def discrete_residual(t, y_pred):

        beta = tf.math.sigmoid(beta_raw)
        q = tf.math.sigmoid(q_raw)
        rho = tf.math.sigmoid(rho_raw)
        xi = tf.math.sigmoid(xi_raw)
        gamma = tf.math.sigmoid(gamma_raw)


        A_pred = y_pred[:, 0:1]
        R_pred = y_pred[:, 1:2]
        I_pred = y_pred[:, 2:3]
        S_pred = y_pred[:, 3:4]


        A_now  = A_pred[:-1]
        R_now  = R_pred[:-1]
        I_now  = I_pred[:-1]
        S_now  = S_pred[:-1]


        A_next = A_pred[1:]
        R_next = R_pred[1:]
        I_next = I_pred[1:]
        S_next = S_pred[1:]


        A_model = A_now + 0.1*(xi - gamma*A_now)
        R_model = R_now + 0.1*(-q*R_now*A_now + beta*S_now)
        I_model = I_now + 0.1*(q*R_now*A_now - rho*I_now)
        S_model = S_now + 0.1*(-beta*S_now + rho*I_now)


        r_A = A_next - A_model
        r_R = R_next - R_model
        r_I = I_next - I_model
        r_S = S_next - S_model


        return [
            r_A,
            r_R,
            r_I,
            r_S
        ]

    geom = dde.geometry.TimeDomain(data_t[0,0], data_t[-1,0])

    y_noise = data_y + np.random.normal(loc=0, scale=data_y.std(axis=0), size=data_y.shape) * noise_level

    observe_A = dde.icbc.PointSetBC(
        data_t,
        y_noise[:,0:1],
        component=0
    )

    observe_R = dde.icbc.PointSetBC(
        data_t,
        y_noise[:, 1:2],
        component = 1
    )

    observe_I = dde.icbc.PointSetBC(
        data_t,
        y_noise[:, 2:3],
        component = 2
    )

    observe_S = dde.icbc.PointSetBC(
        data_t,
        y_noise[:, 3:4],
        component = 3
    )

    data = dde.data.PDE(
    geom,
    discrete_residual,
    [
        observe_A,
        observe_R,
        observe_I,
        observe_S,
    ],
    num_domain=0,
    num_boundary=0,
    anchors=data_t,
)

    net = dde.nn.FNN([1] + [neurons] * layers + [4], activation, "Glorot normal")

    def feature_transform(t):
        t = t / data_t[-1,0]
        return t

    net.apply_feature_transform(feature_transform)

    # Instantiate the model after defining data and net
    model = dde.Model(data, net)

    model.compile(
    "adam",
    lr=1e-3,
    loss_weights=8*[1],
    external_trainable_variables=variable_list
)

    variable = dde.callbacks.VariableValue(
        variable_list,
        period=5000,
        filename=variable_filename,
        precision=8
    )

    model.train(
    iterations=30000,
    callbacks=[variable]
)

    return model, variable

from scipy.special import expit

for noise_level in noise_levels:
    print(f"Training with noise level: {noise_level}")
    variable_filename = f"variables_{int(noise_level * 100)}percent.dat"

    trial_predictions = []
    for trial in range(n_trials):
        print(f"--- Running Trial {trial + 1}/{n_trials} ---")
        seed = int((noise_level * 1000) + trial)
        dde.config.set_random_seed(seed)
        np.random.seed(seed)
        tf.random.set_seed(seed)

        model, variable = dinn(t_train, y_clean, noise_level, variable_filename=variable_filename)
        trial_predictions.append(expit(variable.value))
        tf.keras.backend.clear_session()

parameters_history_by_noise = {}

parameter_names = [
    "beta",
    "q",
    "rho",
    "xi",
    "gamma",
]

for noise_level in noise_levels:
    variable_filename = f"variables_{int(noise_level * 100)}percent.dat"

    lines = open(variable_filename, "r").readlines()

    raw_parameters_pred_history = np.array(
        [
            np.fromstring(
                min(
                    re.findall(
                        re.escape("[") + "(.*?)" + re.escape("]"),
                        line
                    ),
                    key=len
                ),
                sep=",",
            )
            for line in lines
        ]
    )

    iterations = [
        int(re.findall("^[0-9]+", line)[0])
        for line in lines
    ]

    parameters_pred_history = {
        name: expit(raw_parameters_pred_history[:, i])
        for i, name in enumerate(parameter_names)
    }

    parameters_history_by_noise[
        f"{int(noise_level * 100)}%"
    ] = parameters_pred_history

    n_callbacks, n_variables = raw_parameters_pred_history.shape

    fig, axes = plt.subplots(
        nrows=n_variables,
        sharex=True,
        figsize=(10, 14),
        layout="constrained"
    )

    # Plot all five parameters
    for ax, parameter in zip(axes, parameter_names):
        parameter_value = parameters_real[parameter]

        ax.plot(
            iterations,
            parameters_pred_history[parameter],
            "-",
            label="Estimation"
        )

        ax.hlines(
            parameter_value,
            xmin=0,
            xmax=iterations[-1],
            linestyles="dashed",
            color=sns.color_palette()[1],
            label="Actual"
        )

        ax.set_ylabel(parameter)
        ax.legend(loc="center left", bbox_to_anchor=(1, 0.5))

    # These happen ONCE per noise level
    axes[-1].set_xlabel("Iterations")

    fig.suptitle(
        f"Parameter estimation with noise level: {noise_level}"
    )

    output_filename = f"plot-noiselevel{noise_level}.png"

    print(f"Saving {output_filename}")

    fig.savefig(output_filename)

    plt.close(fig)

import re
import numpy as np
import pandas as pd
from scipy.special import expit


parameters_real = {
    "beta": 0.001,
    "q": 0.55,
    "rho": 0.1,
    "xi": 0.004,
    "gamma": 0.008,
}

parameter_names = [
    "beta",
    "q",
    "rho",
    "xi",
    "gamma",
]

noise_levels = [0.01, 0.05, 0.10, 0.20]

results = []

for noise_level in noise_levels:

    filename = (
        f"variables_{int(noise_level * 100)}percent.dat"
    )

    with open(filename, "r") as f:
        lines = f.readlines()

    if not lines:
        raise ValueError(f"{filename} is empty")

    # Final training checkpoint
    last_line = lines[-1]

    matches = re.findall(r"\[(.*?)\]", last_line)

    if not matches:
        raise ValueError(
            f"Could not parse parameter values from {filename}"
        )

    raw_values = np.fromstring(
        min(matches, key=len),
        sep=","
    )

    if len(raw_values) != len(parameter_names):
        raise ValueError(
            f"Expected {len(parameter_names)} parameters "
            f"in {filename}, found {len(raw_values)}"
        )

    predicted_values = expit(raw_values)

    for name, predicted in zip(
        parameter_names,
        predicted_values
    ):
        actual = parameters_real[name]

        results.append({
            "noise_percent": noise_level * 100,
            "parameter": name,
            "actual": actual,
            "predicted": predicted,
            "error_percent":
                abs(predicted - actual) / actual * 100,
        })


results_df = pd.DataFrame(results)

print(
    results_df.to_string(
        index=False,
        float_format=lambda x: f"{x:.6f}"
    )
)