# -*- coding: utf-8 -*-
"""LatestSobolSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ymLsW43VoJQH6cBp8u0pkIhSq2E_ma1
"""

!pip install SALib

import time

from SALib.sample import saltelli
from SALib.analyze import sobol
import numpy as np

# Setup and constants

INTERVAL = [0, 1500]
POINTS_ALONG_INTERVAL = 101

# parameter order: beta, delta_1, delta_2, rho, u, gamma, p, xi
TRUE_PARAMETER = (
    0.001,
    0.5,
    0.5,
    0.1,
    0.1,
    0.008,
    1,
    0.004,
)

PARAMETER_SYMBOLS = [
    r"$\beta$",
    r"$\delta_1$",
    r"$\delta_2$",
    r"$\rho$",
    r"$u$",
    r"$\gamma$",
    r"$p$",
    r"$\xi$",
]

# state order: R, I, S, A
INITIAL_CONDITION = [
    1,
    0,
    0,
    0,
]

BOUND_FACTOR = 0.25
POINTS = 2 ** 10

ZERO_PARAMETER_UPPER = 0.05

CALC_SECOND_ORDER = False

# Build the sampling problem and draw the parameter samples

problem = {
    "num_vars": len(PARAMETER_SYMBOLS),
    "names": PARAMETER_SYMBOLS,
    "bounds": [],
}

for ii in range(len(TRUE_PARAMETER)):
    baseline_value = TRUE_PARAMETER[ii]

    if baseline_value == 0:
        lower_bound = 0
        upper_bound = ZERO_PARAMETER_UPPER
    else:
        lower_bound = baseline_value * (1 - BOUND_FACTOR)
        upper_bound = baseline_value * (1 + BOUND_FACTOR)

    problem["bounds"].append([lower_bound, upper_bound])

inputs = saltelli.sample(problem, POINTS, calc_second_order=CALC_SECOND_ORDER)
n_samples = inputs.shape[0]

# Time grid

WEEK_SPACING = 0.1

num_time_steps = INTERVAL[1] - INTERVAL[0]        # 1500 outer steps
dt_step = WEEK_SPACING / (POINTS_ALONG_INTERVAL - 1)  # 100 Euler steps of 0.001 per outer step

t = [(ii + 1) * WEEK_SPACING for ii in range(num_time_steps)]

# Run the model for ALL parameter samples at once

beta    = inputs[:, 0]
delta_1 = inputs[:, 1]
delta_2 = inputs[:, 2]
rho     = inputs[:, 3]
u       = inputs[:, 4]
gamma   = inputs[:, 5]
p       = inputs[:, 6]
xi      = inputs[:, 7]

R = np.full(n_samples, float(INITIAL_CONDITION[0]))
I = np.full(n_samples, float(INITIAL_CONDITION[1]))
S = np.full(n_samples, float(INITIAL_CONDITION[2]))
A = np.full(n_samples, float(INITIAL_CONDITION[3]))

I_outputs = np.empty((num_time_steps, n_samples), dtype=float)

print(f"Simulating {n_samples} samples x {num_time_steps * (POINTS_ALONG_INTERVAL - 1)} Euler steps ...")
start = time.time()

for ii_sub in range(num_time_steps):
    for _ in range(POINTS_ALONG_INTERVAL - 1):
        # R -> I flow driven by A. delta_1 and delta_2*u are the two routes in;
        # written as one product because they always appear multiplied by p*A*R.
        infection = p * A * R * (delta_1 + delta_2 * u)

        dRdt = beta * S - infection
        dIdt = infection - rho * I
        dSdt = rho * I - beta * S
        dAdt = xi - gamma * A

        R = np.maximum(R + dt_step * dRdt, 0.0)
        I = np.maximum(I + dt_step * dIdt, 0.0)
        S = np.maximum(S + dt_step * dSdt, 0.0)
        A = np.maximum(A + dt_step * dAdt, 0.0)

    I_outputs[ii_sub] = np.where(np.isfinite(I), I, np.nan)

    if (ii_sub + 1) % max(1, num_time_steps // 10) == 0:
        elapsed = time.time() - start
        print(f"  time step {ii_sub + 1}/{num_time_steps}  ({elapsed:.1f}s)")

print(f"Simulation finished in {time.time() - start:.1f}s")

# Sobol sensitivity analysis at each time step

Si_I_F = []
Si_I_T = []

print(f"Running Sobol analysis at {num_time_steps} time steps ...")
analysis_start = time.time()

for ii in range(num_time_steps):
    sobol_analysis_I = sobol.analyze(
        problem,
        I_outputs[ii],
        calc_second_order=CALC_SECOND_ORDER,
        print_to_console=False,
    )

    Si_I_F.append(sobol_analysis_I["S1"])
    Si_I_T.append(sobol_analysis_I["ST"])

print(f"Analysis finished in {time.time() - analysis_start:.1f}s")

Si_I_F = np.clip(np.array(Si_I_F), 0, 1)
Si_I_T = np.clip(np.array(Si_I_T), 0, 1)

# Save results

np.save("t_sir.npy", np.array(t))
np.save("Si_I_F.npy", Si_I_F)
np.save("Si_I_T.npy", Si_I_T)
np.save("PARAMETER_SYMBOLS_sir.npy", np.array(PARAMETER_SYMBOLS, dtype=object))

print("Saved: t_sir.npy, Si_I_F.npy, Si_I_T.npy, PARAMETER_SYMBOLS_sir.npy")

import numpy as np
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

# Load results

t = np.load("t_sir.npy")
Si_I_F = np.load("Si_I_F.npy")   # first-order,  shape (time, params)
Si_I_T = np.load("Si_I_T.npy")   # total-order,  shape (time, params)
labels = list(np.load("PARAMETER_SYMBOLS_sir.npy", allow_pickle=True))

num_params = Si_I_F.shape[1]

# Give each parameter one consistent color across both panels.
colors = plt.cm.tab10(np.linspace(0, 1, num_params))

importance = np.nanmean(Si_I_T, axis=0)
order = np.argsort(importance)[::-1]

# Draw
fig, (ax_first, ax_total) = plt.subplots(1, 2, figsize=(13, 5.5), sharey=True)

for ax, data, title in (
    (ax_first, Si_I_F, "First-order"),
    (ax_total, Si_I_T, "Total-order"),
):
    for k in order:
        ax.plot(t, data[:, k], color=colors[k], linewidth=1.6, label=labels[k])
    ax.set_title(title)
    ax.set_xlabel("Weeks")
    ax.set_ylim(-0.02, 1.02)
    ax.grid(True, alpha=0.3)

ax_first.set_ylabel("Sobol sensitivity index for I")

handles, legend_labels = ax_total.get_legend_handles_labels()
fig.legend(
    handles,
    legend_labels,
    loc="center right",
    title="parameter\n",
    frameon=True,
)

fig.suptitle("Sensitivity of the I group to each parameter over time", fontsize=13)
fig.tight_layout(rect=[0, 0, 0.88, 1])  # leave room on the right for the legend

fig.savefig("sens_indices.png", dpi=150)
print("Saved: sens_indices.png")